name: feature_build_lint

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build:
    name: Build and Check for Errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install UV
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Generate Requirements
        run: |
          uv pip compile pyproject.toml > requirements.txt
      - name: Create virtual environment
        run: |
          uv venv
      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
      - name: Print Build Success Message
        run: echo "Build Successful!!"

  lint:
    name: Lint Code with Pylint
    runs-on: ubuntu-latest
    needs: build   # <--- This makes lint depend on build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install UV
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Generate Requirements
        run: |
          uv pip compile pyproject.toml > requirements.txt
      - name: Create virtual environment
        run: |
          uv venv
      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
      - name: Activate environment
        run: |
          source .venv/bin/activate
      - name: Install pylint
        run: |
          uv pip install pylint
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Run Pylint
        run: |
          uv run pylint $(git ls-files '*.py')